[tool.towncrier]
    directory = "changelog.d"
    filename = "CHANGES.md"
    name = "Changes in Element"
    template = "tools/towncrier/template.md"
    issue_format = "[#{issue}](https://github.com/element-hq/element-android/issues/{issue})"

    [[tool.towncrier.type]]
        directory = "feature"
        name = "Features ✨"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "sdk"
        name = "SDK API changes ⚠️"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "misc"
        name = "Other changes"
        showcontent = true
